import Head from 'next/head'
import { Hero } from '@/components/Hero'
import { Header } from '@/components/Header'
import { Projects } from '@/components/Projects'
import { MySkills } from '@/components/MySkills'
import { Footer } from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-20">
        <Header />
        <Hero />
        <Projects />
        <MySkills />
        <Footer />
      </main>
    </>
  )
}
